[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"

[rpc_endpoints]
baseSepolia = "https://sepolia.base.org"  # Ensure this is correctly set

[etherscan]
baseSepolia = { key = "2HYWGYW5YDKX4WF9MXIJNHYP9HXPVZXEBJ", url = "https://api-sepolia.basescan.org/api" }
